export const colors = {
  button: {
    primary: {
      background: '#58C2B4',
      color: '#fff',
      hover: '#6FDCCB',
      click: '#3FA99B',
      disabled: '#D6E1EE',
      disabledColor: 'rgba(33,54,79,0.4)',
      letterSpacing: '1.29px',
      lineHeight: '16px',
      fontFamily: '"Open Sans", sans-serif',
      fontSize: '14px',
      boxShadow: '0 0 8px 0 rgba(88,194,180,0.16)',
    },
    secondary: {
      boxSizing: 'border-box',
      height: '36px',
      width: '182px',
      border: '2px solid #58C2B4',
      color: '#2B9486',
      background: 'none',
      boxShadow: '0 0 8px 0 rgba(88,194,180,0.16)',
      fontFamily: '"Open Sans", sans-serif',
      fontSize: '14px',
      letterSpacing: '1.29px',
      lineHeight: '16px',
      hover: '#D8F5F5',
      click: '#B4F1EA',
      disabled: 'none',
      disabledColor: '#A6A6B0',
    },
  },
};
